### ISSUE TITLE
I want to add Image to pdf file using this library....I tried alot...But i am not able to do this.Can someone help me in adding image as logo to pdf file.

### ISSUE THREAD

**Issue by navjotdeol** [pug-pelle-p/pugpdf#3]

**Comment by pug-pelle-p** [comment]
Hi, I just added an example on how to do this in: /PugPdf.SampleNetCore/Program.cs
Hope that helps :)

**Comment by navjotdeol** [comment]
> Hi, I just added an example on how to do this in: /PugPdf.SampleNetCore/Program.cs
> Hope that helps :)

Its amazing. Thanks a lot for the wonderful example. Now I created a nice pdf file with logo.

**Comment by pug-pelle-p** [comment]
Glad I could help :)
