### ISSUE TITLE
Headers/Footers/Misc

### ISSUE THREAD

**Issue by obrienmn** [pug-pelle-p/pugpdf#4]
Hi there,

Is there any interest in extending the wrapper to support the configuration of headers, footers, and a few other switches (such as --lowquality, --print-media-type, and --grayscale)?

If so, I'm happy to submit a pull request.

Cheers

**Comment by pug-pelle-p** [comment]
Yes, i'm very interested in that, I'll gladly take a PR for that :)

**Comment by obrienmn** [comment]
Excellent.

The PR has been created.

Thanks!
